# Generated by Django 3.2.25 on 2024-09-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0007_auto_20240314_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlbackend',
            name='selected_model_name',
            field=models.TextField(blank=True, default='', help_text='Name of selected model to use with the connected backend', null=True, verbose_name='selected model name'),
        ),
    ]
