title: Object Detection with Bounding Boxes
type: community
group: Computer Vision
order: 3
image: /static/templates/object-detection-with-bounding-boxes.png
details: <h1>Draw a bounding box around the object</h1>
config: |
  <View>
    <Image name="image" value="$image"/>
    <RectangleLabels name="label" toName="image">
      <Label value="Label 0" alias="LABEL_0" background="orange"/>
      <Label value="Label 1" alias="LABEL_1" background="red"/>
      <Label value="Label 2" alias="LABEL_2" background="blue"/>
      <Label value="Label 3" alias="LABEL_3" background="green"/>
      <Label value="Label 4" alias="LABEL_4" background="yellow"/>
      <Label value="Label 5" alias="LABEL_5" background="purple"/>
    </RectangleLabels>
  </View>
